version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t iris-model .
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build process finished.


