version: 0.2

phases:
  pre_build:
    commands:
      - echo "Decrypting Docker password..."
      - DOCKER_PASSWORD=$(aws ssm get-parameter --name DOCKER_PASS --with-decryption --query 'Parameter.Value' --output text)
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_PASSWORD" | docker login -u devangkubde88 --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t devangkubde88/iris-ml:latest .
      - echo "Pushing Docker image to Docker Hub..."
      - docker push devangkubde88/iris-ml:latest
      - echo "Pulling image and running it to verify output..."
      - docker pull devangkubde88/iris-ml:latest
      - docker run --rm devangkubde88/iris-ml:latest

  post_build:
    commands:
      - echo "Build, push, and run complete."



