version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  build:
    commands:
      - echo Setting up Docker Buildx...
      - docker buildx create --use
      - docker buildx build --platform linux/arm64 -t $DOCKER_USER/iris-ml:latest --push .

