RecipeFormatVersion: '2020-01-25'
ComponentName: com.ml.inference
ComponentVersion: 1.0.0
ComponentDescription: "ML inference container using Docker on Raspberry Pi"
ComponentPublisher: "Devang"
ComponentType: aws.greengrass.generic

Manifests:
  - Platform:
      os: linux
      architecture: armv7
    Artifacts:
      - URI: devangkubde88/iris-ml
    Lifecycle:
      install: |-
        echo "✅ No install step needed. Docker image will be pulled during run."
      run: |-
        echo "🚀 Running ML inference Docker container..."
        docker pull devangkubde88/iris-ml
        docker run --rm \
          --name ml-inference \
          --network host \
          devangkubde88/iris-ml
      shutdown: |-
        echo "🛑 Stopping container (if needed)..."
        docker stop ml-inference || true

    Permissions:
      - Docker: true

Lifecycle:
  Install:
    Script: echo "No component install script needed."
  Run:
    Script: echo "Run handled in Docker lifecycle."



