---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.devangkubde.irisml
ComponentVersion: 1.0.0
ComponentType: aws.greengrass.generic
ComponentDescription: ML Iris model docker container
ComponentPublisher: Devang Kubde
Manifests:
  - Platform:
      os: linux
      architecture: armv7l
    Lifecycle:
      Run: docker run --rm devangkubde88/iris-ml:latest


