RecipeFormatVersion: '2020-01-25'
ComponentName: com.devangkubde.irisml
ComponentVersion: 1.0.0
ComponentDescription: ML Iris model docker container
ComponentPublisher: Devang Kubde
ComponentType: aws.greengrass.generic

Manifests:
  - Platform:
      os: linux
      architecture: armv7l
    Artifacts:
      - URI: docker:devangkubde88/iris-ml
    Lifecycle:
      install: |-
        echo "✅ No installation needed"
      run: |-
        echo "🚀 Pulling and running Docker container"
        docker pull devangkubde88/iris-ml
        docker run --rm \
          --name iris-ml-inference \
          --network host \
          devangkubde88/iris-ml
      shutdown: |-
        echo "🛑 Attempting to stop container..."
        docker stop iris-ml-inference || true

    Permissions:
      - Docker: true
